export default
[{title: "Build a Discord clone with React.Js",
views:"5.3M Views",
description: "Make your own cloen",
subs :"100k",
timestamp:"1 days ago",
channelImage:"https://yt3.ggpht.com/a-/AOh14GhOUP_9re93yOMdN4RLQLHl6Mbk6vmUS1524w=s68-c-k-c0x00ffffff-no-rj-mo",
channel:"Clever Programmer",
image:"https://i.ytimg.com/vi/zc1loX80TX8/hq720_live.jpg?sqp=CLTK_fsF-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB2SZhFhcknHvmn4yvginwNE69Bog"
},

{title:"chill and nudisco",
views:"2.3M Views",
description: "Make your own cloen",
subs :"100k",
timestamp:"3 days ago",
channelImage:"https://yt3.ggpht.com/a/AATXAJy0tCr1ErmcenA4pmE--sfHb5NQweIyvtN52Q5TyA=s88-c-k-c0x00ffffff-no-rj",
channel:";D LUV MUZIK",
image:"https://i.ytimg.com/vi/uaWSwV61jkU/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBHYiB1qkGYsVB5EC6gduxrd3Gv-A"}
,

{title:"LAZzzy song",
views:"2.3M Views",
description: "Make your own cloen",
subs :"100k",
timestamp:"3 days ago",
channelImage:"https://yt3.ggpht.com/a-/AOh14Gh8mCsMr1UteD11x_lU9aX7x95xV6Q37HzvMQ=s68-c-k-c0x00ffffff-no-rj-mo",
channel:";D LUV MUZIK",
image:"https://i.ytimg.com/vi/0UKwpJUUDlM/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBisvVbcrgRc-l45eJUOd0nNh7BTg"}, {        title:"sounds good!",
views:"2.3M Views",
description: "Make your own cloen",
subs :"100k",
timestamp:"3 days ago",
channelImage:"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.Jbm7P8PO0ABnbo4P0G8hdwHaE2%26pid%3DApi&f=1",
channel:";D LUV MUZIK",
image:"https://i.ytimg.com/an_webp/B7BQP7T4iW0/mqdefault_6s.webp?du=3000&sqp=CLC8gvwF&rs=AOn4CLBP6I6EYT1it4PfgVGg2vOC3oYx3g"},{        title:"Konstanza",
views:"2.3M Views",
description: "Make your own cloen",
subs :"100k",
timestamp:"3 days ago",
channelImage:"https://yt3.ggpht.com/a-/AOh14GiszV6auYGyWrbO-SAmevgOTlgTemYXSePQQw=s68-c-k-c0x00ffffff-no-rj-mo",
channel:";D LUV MUZIK",
image:"https://i.ytimg.com/vi/HF65cySUYao/hq720_live.jpg?sqp=CNjhgvwF-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAg04YOTVrU-aJGIAubSnFjAu3YGw"},{        title:"✨✨⭐️✨✨🌙✨✨ sleeping peel ✨🌟✨✨✨💫✨✨",
views:"2.3M Views",
description: "Make your own cloen",
subs :"100k",
timestamp:"3 days ago",
channelImage:"https://yt3.ggpht.com/a-/AOh14GiqGrGWurRyElA1z8ta0tcGqj7mZDfolJHloQ=s68-c-k-c0x00ffffff-no-rj-mo",
channel:";D LUV MUZIK",
image:"https://i.ytimg.com/an_webp/PqCLaYjtGUU/mqdefault_6s.webp?du=3000&sqp=CPizgvwF&rs=AOn4CLDlk2ThG8Xq74274hV7cm5NZaxdEw"},{        title:"chill and nudisco",
views:"2.3M Views",
description: "Make your own cloen",
subs :"100k",
timestamp:"3 days ago",
channelImage:"https://yt3.ggpht.com/a/AATXAJy0tCr1ErmcenA4pmE--sfHb5NQweIyvtN52Q5TyA=s88-c-k-c0x00ffffff-no-rj",
channel:";D LUV MUZIK",
image:"https://i.ytimg.com/vi/uaWSwV61jkU/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBHYiB1qkGYsVB5EC6gduxrd3Gv-A"},{        title:"Lazyyy song",
views:"2.3M Views",
description: "Make your own cloen",
subs :"100k",
timestamp:"3 days ago",
channelImage:"https://yt3.ggpht.com/a-/AOh14Gh8mCsMr1UteD11x_lU9aX7x95xV6Q37HzvMQ=s68-c-k-c0x00ffffff-no-rj-mo",
channel:";D LUV MUZIK",
image:"https://i.ytimg.com/vi/0UKwpJUUDlM/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBisvVbcrgRc-l45eJUOd0nNh7BTg"}
]